apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bonicare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: keroliskhalaf1/bonicare-frontend:<COMMIT_SHA>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bonicare
spec:
  selector:
    app: frontend
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30200
  type: NodePort