pipeline {

    agent any

    options {
        timestamps()
        ansiColor('xterm')
        disableConcurrentBuilds()

        buildDiscarder(logRotator(
            numToKeepStr: '20',
            artifactNumToKeepStr: '10'
        ))
    }

    environment {

        DOCKER_BUILDKIT = "1"
        COMPOSE_DOCKER_CLI_BUILD = "1"

        REGISTRY = "docker.io"
        NAMESPACE = "keroliskhalaf1"
    }

    stages {

        stage('Checkout Repository') {
            steps {

                cleanWs()

                git(
                    branch: 'main',
                    url: 'https://github.com/KerolisKhalaf/bonicare-platform-devops.git'
                )

                script {

                    env.GIT_SHA = sh(
                        script: 'git rev-parse --short=12 HEAD',
                        returnStdout: true
                    ).trim()

                    env.IMAGE_TAG = env.GIT_SHA
                }

                echo "Building Branch: main"
                echo "Commit: ${env.GIT_SHA}"
                echo "Image Tag: ${env.IMAGE_TAG}"
            }
        }

        stage('Docker Information') {
            steps {

                sh '''
                    docker version
                    docker buildx version
                    docker info
                '''
            }
        }

        stage('Docker Login') {
            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub_id',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh '''
                        echo "$DOCKER_PASS" | docker login \
                            -u "$DOCKER_USER" \
                            --password-stdin
                    '''
                }
            }
        }

        stage('Create Buildx Builder') {
            steps {

                sh '''
                    docker buildx inspect bonicare-builder >/dev/null 2>&1 || \
                    docker buildx create \
                        --name bonicare-builder \
                        --driver docker-container

                    docker buildx use bonicare-builder

                    docker buildx inspect --bootstrap
                '''
            }
        }

        stage('Build & Push Images') {
            steps {

                withEnv([
                    "VERSION=${IMAGE_TAG}",
                    "REGISTRY=${REGISTRY}",
                    "NAMESPACE=${NAMESPACE}"
                ]) {

                    sh '''
                        docker buildx bake \
                            --push \
                            --file ci/docker-bake.hcl
                    '''
                }
            }
        }
    }

    post {

        success {
            echo 'CI Pipeline Finished Successfully'
            echo "Images pushed with tag: ${IMAGE_TAG}"
        }

        failure {
            echo 'CI Pipeline Failed'
        }

        always {

            sh 'docker logout || true'

            cleanWs()
        }
    }
}